version: '3.7'

volumes:
  database:
    external: true

networks:
  net:
    external: true
    driver: bridge

services:

  db:
    image: mongo:latest
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - database:/data/db:rw
    networks:
      - net

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@db:27017/
      ME_CONFIG_SITE_BASEURL: /mongoadmin/   
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - net

  backend:
    container_name: backend
    build: 
      context: ./backend
    restart: always
    ports:
      - 8085:8085
    networks:
      - net
  
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
    restart: always
    ports:
      - 8888:8888
    networks:
      - net
